
// Generated by MyGeneration Version # (1.1.6.0)

using System;

namespace NCI.EasyObjects.Tests.SQL
{
	public class EmployeeDepartmentHistory : _EmployeeDepartmentHistory
	{		
		public EmployeeDepartmentHistory() {}

		// Place your custom code here.
	}
}
