
// Generated by MyGeneration Version # (1.3.0.1)

using System;
using System.Data;
using System.Data.Common;

namespace NCI.EasyObjects.Tests.SQL
{
	public class IdentityOnlyTest : _IdentityOnlyTest
	{		
		public IdentityOnlyTest() 
		{
			this.DefaultCommandType = CommandType.StoredProcedure;
		}

		// Place your custom code here.
	}
}
