
// Generated by MyGeneration Version # (1.1.7.7)

using System;

namespace NCI.EasyObjects.Tests.Oracle
{
	public class EmployeeDeptHist : _EmployeeDeptHist
	{		
		public EmployeeDeptHist() {}

		// Place your custom code here.
	}
}
