'===============================================================================
'  Generated From - VbNet_EasyObject_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  
'  This object is 'MustInherit' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  Public Class YourObject 
'      Inherits _YourObject
'
'  End Class
'
'===============================================================================

' Generated by MyGeneration Version # (1.1.4.0)

Imports System
Imports System.Data
Imports System.Configuration
Imports System.Collections
Imports System.Collections.Specialized
Imports System.Xml
Imports System.IO

Imports Microsoft.Practices.EnterpriseLibrary.Data
Imports NCI.EasyObjects


#Region " Schema "

Public Class ShippersSchema
	Inherits NCI.EasyObjects.Schema

    Private Shared _entries As ArrayList
	Public Shared ShipperID As New SchemaItem("ShipperID", DbType.Int32, True, False, False, True, True, False)
	Public Shared CompanyName As New SchemaItem("CompanyName", DbType.String, SchemaItemJustify.None, 40, False, False, False, False)
	Public Shared Phone As New SchemaItem("Phone", DbType.String, SchemaItemJustify.None, 24, True, False, False, False)

    Public Overrides ReadOnly Property SchemaEntries() As ArrayList
        Get
            If _entries Is Nothing Then
                _entries = New ArrayList()
				_entries.Add(ShippersSchema.ShipperID)
				_entries.Add(ShippersSchema.CompanyName)
				_entries.Add(ShippersSchema.Phone)

            End If
            Return _entries
        End Get
    End Property

End Class

#End Region

Public MustInherit Class _Shippers
    Inherits EasyObject

    Sub New()
        Dim _schema As New ShippersSchema()
        Me.SchemaEntries = _schema.SchemaEntries
		Me.SchemaGlobal = "dbo"
    End Sub

	Public Overrides Sub FlushData()
		Me._whereClause = Nothing
		Me._aggregateClause = Nothing
		MyBase.FlushData()
	End Sub
		
	''' <summary>
	''' Loads the business object with info from the database, based on the requested primary key.
	''' </summary>
	''' <param name="ShipperID"></param>
	''' <returns>A Boolean indicating success or failure of the query</returns>
	Public Function LoadByPrimaryKey(ByVal ShipperID As Integer) As Boolean
		
		Select Case Me.DefaultCommandType
			Case CommandType.StoredProcedure
				Dim parameters As ListDictionary = New ListDictionary

				' Add in parameters
				parameters.Add(ShippersSchema.ShipperID.FieldName, ShipperID)

				Return MyBase.LoadFromSql(Me.SchemaStoredProcedureWithSeparator & "daab_GetShippers", parameters, CommandType.StoredProcedure)
				
			Case CommandType.Text
				Me.Where.ShipperID.Value = ShipperID
				Return Me.Query.Load()

			Case Else
				Throw New ArgumentException("Invalid CommandType", "commandType")
				
		End Select
		
	End Function

    ''' <summary>
    ''' Loads all records from the table.
    ''' </summary>
    ''' <returns>A Boolean indicating success or failure of the query</returns>
    Public Function LoadAll() As Boolean
	
		Select Case Me.DefaultCommandType
		
			Case CommandType.StoredProcedure
				Dim parameters As ListDictionary = Nothing
				Return MyBase.LoadFromSql(Me.SchemaStoredProcedureWithSeparator & "daab_GetAllShippers", parameters, CommandType.StoredProcedure)
				
			Case CommandType.Text
				Return Me.Query.Load()
			
			Case Else
				Throw New ArgumentException("Invalid CommandType", "commandType")
				
		End Select

    End Function

    ''' <summary>
    ''' Adds a new record to the internal table.
    ''' </summary>
	Public Overrides Sub AddNew()
		MyBase.AddNew()

	End Sub

    Protected Shadows Function GetInsertCommand(commandType As CommandType) As DBCommandWrapper
	
		Dim dbCommandWrapper As DBCommandWrapper
		
        ' Create the Database object, using the default database service. The
        ' default database service is determined through configuration.
        Dim db As Database = GetDatabase()
	
		Select Case commandType
		
			Case CommandType.StoredProcedure
				Dim sqlCommand As String = Me.SchemaStoredProcedureWithSeparator & "daab_AddShippers"
				dbCommandWrapper = db.GetStoredProcCommandWrapper(sqlCommand)
		
				CreateParameters(dbCommandWrapper)
				
				' Add autokey parameters
				dbCommandWrapper.AddParameter("ShipperID", DbType.Int32, 0, ParameterDirection.Output, True, 0, 0, "ShipperID", DataRowVersion.Default, Convert.DBNull)
				
			Case CommandType.Text
				Me.Where.WhereClauseReset()
				For Each item As SchemaItem In Me.SchemaEntries
					If Not (item.IsAutoKey OrElse item.IsComputed)
						Me.Query.AddInsertColumn(item)
					End If
				Next
				dbCommandWrapper = Me.Query.GetInsertCommandWrapper()

				dbCommandWrapper.Command.Parameters.Clear()
				dbCommandWrapper.AddParameter("ShipperID", DbType.Int32, 0, ParameterDirection.Output, True, 0, 0, "ShipperID", DataRowVersion.Default, Convert.DBNull)
				CreateParameters(dbCommandWrapper)

			Case Else
				Throw New ArgumentException("Invalid CommandType", "commandType")
				
		End Select

        Return dbCommandWrapper

    End Function

    Protected Shadows Function GetUpdateCommand(commandType As CommandType) As DBCommandWrapper
	
		Dim dbCommandWrapper As DBCommandWrapper

        ' Create the Database object, using the default database service. The
        ' default database service is determined through configuration.
        Dim db As Database = GetDatabase()
	
		Select Case commandType
		
			Case CommandType.StoredProcedure
				Dim sqlCommand As String = Me.SchemaStoredProcedureWithSeparator & "daab_UpdateShippers"
				dbCommandWrapper = db.GetStoredProcCommandWrapper(sqlCommand)
		
				CreateParameters(dbCommandWrapper)
		
				' Add autokey parameters
				dbCommandWrapper.AddInParameter("ShipperID", DbType.Int32, "ShipperID", DataRowVersion.Current)

			Case CommandType.Text
				Me.Where.WhereClauseReset()
				For Each item As SchemaItem In Me.SchemaEntries
					If Not (item.IsAutoKey OrElse item.IsComputed)
						Me.Query.AddInsertColumn(item)
					End If
				Next

				Me.Where.WhereClauseReset()
				Me.Where.ShipperID.Operator = WhereParameter.Operand.Equal
				dbCommandWrapper = Me.Query.GetUpdateCommandWrapper()

				dbCommandWrapper.Command.Parameters.Clear()
				CreateParameters(dbCommandWrapper)
				dbCommandWrapper.AddInParameter("ShipperID", DbType.Int32, "ShipperID", DataRowVersion.Current)

			Case Else
				Throw New ArgumentException("Invalid CommandType", "commandType")
				
		End Select

        Return dbCommandWrapper

    End Function

    Protected Shadows Function GetDeleteCommand(commandType As CommandType) As DBCommandWrapper
	
		Dim dbCommandWrapper As DBCommandWrapper

        ' Create the Database object, using the default database service. The
        ' default database service is determined through configuration.
        Dim db As Database = GetDatabase()
	
		Select Case commandType
		
			Case CommandType.StoredProcedure
				Dim sqlCommand As String = Me.SchemaStoredProcedureWithSeparator & "daab_DeleteShippers"
				dbCommandWrapper = db.GetStoredProcCommandWrapper(sqlCommand)
		
				' Add primary key parameters
				dbCommandWrapper.AddInParameter("ShipperID", DbType.Int32, "ShipperID", DataRowVersion.Current)

			Case CommandType.Text
				Me.Where.WhereClauseReset()
				Me.Where.ShipperID.Operator = WhereParameter.Operand.Equal
			dbCommandWrapper = Me.Query.GetDeleteCommandWrapper()

			dbCommandWrapper.Command.Parameters.Clear()
				dbCommandWrapper.AddInParameter("ShipperID", DbType.Int32, "ShipperID", DataRowVersion.Current)

			Case Else
				Throw New ArgumentException("Invalid CommandType", "commandType")
				
		End Select

        Return dbCommandWrapper

    End Function

    Private Sub CreateParameters(ByVal dbCommandWrapper As DBCommandWrapper)
		
		dbCommandWrapper.AddInParameter("CompanyName", DbType.String, "CompanyName", DataRowVersion.Current)
		dbCommandWrapper.AddInParameter("Phone", DbType.String, "Phone", DataRowVersion.Current)

    End Sub

#Region " Properties "

	Public Overridable Property ShipperID() As Integer
        Get
			Return Me.GetInteger(ShippersSchema.ShipperID.FieldName)
      End Get
        Set(ByVal Value As Integer)
			Me.SetInteger(ShippersSchema.ShipperID.FieldName, Value)
      End Set
    End Property

	Public Overridable Property CompanyName() As String
        Get
			Return Me.GetString(ShippersSchema.CompanyName.FieldName)
      End Get
        Set(ByVal Value As String)
			Me.SetString(ShippersSchema.CompanyName.FieldName, Value)
      End Set
    End Property

	Public Overridable Property Phone() As String
        Get
			Return Me.GetString(ShippersSchema.Phone.FieldName)
      End Get
        Set(ByVal Value As String)
			Me.SetString(ShippersSchema.Phone.FieldName, Value)
      End Set
    End Property

    Public Overrides ReadOnly Property TableName() As String
        Get
            Return "Shippers"
        End Get
    End Property

#End Region

#Region " String Properties "
		Public Overridable Property s_ShipperID As String
			Get
				If Me.IsColumnNull(ShippersSchema.ShipperID.FieldName) Then
					Return String.Empty
				Else
					Return MyBase.GetIntegerAsString(ShippersSchema.ShipperID.FieldName)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ShippersSchema.ShipperID.FieldName)
				Else
					Me.ShipperID = MyBase.SetIntegerAsString(ShippersSchema.ShipperID.FieldName, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_CompanyName As String
			Get
				If Me.IsColumnNull(ShippersSchema.CompanyName.FieldName) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ShippersSchema.CompanyName.FieldName)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ShippersSchema.CompanyName.FieldName)
				Else
					Me.CompanyName = MyBase.SetStringAsString(ShippersSchema.CompanyName.FieldName, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Phone As String
			Get
				If Me.IsColumnNull(ShippersSchema.Phone.FieldName) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ShippersSchema.Phone.FieldName)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ShippersSchema.Phone.FieldName)
				Else
					Me.Phone = MyBase.SetStringAsString(ShippersSchema.Phone.FieldName, Value)
				End If
			End Set
		End Property


#End Region

#Region " Where Clause "
    Public Class WhereClause

        Public Sub New(ByVal entity As EasyObject)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffWhereParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffWhereParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region " TearOff's "
		Public class TearOffWhereParameter
		
			Private _clause as WhereClause
			
			Public Sub New(ByVal clause As WhereClause)
				Me._clause = clause
			End Sub

			Public ReadOnly Property ShipperID() As WhereParameter
				Get
					Dim wp As WhereParameter = New WhereParameter(ShippersSchema.ShipperID)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddWhereParameter(wp)
					Return wp
				End Get
			End Property

			Public ReadOnly Property CompanyName() As WhereParameter
				Get
					Dim wp As WhereParameter = New WhereParameter(ShippersSchema.CompanyName)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddWhereParameter(wp)
					Return wp
				End Get
			End Property

			Public ReadOnly Property Phone() As WhereParameter
				Get
					Dim wp As WhereParameter = New WhereParameter(ShippersSchema.Phone)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddWhereParameter(wp)
					Return wp
				End Get
			End Property

	End Class
	
	#End Region	

		Public ReadOnly Property ShipperID() As WhereParameter 
			Get
				If _ShipperID_W Is Nothing Then
					_ShipperID_W = TearOff.ShipperID
				End If
				Return _ShipperID_W
			End Get
		End Property

		Public ReadOnly Property CompanyName() As WhereParameter 
			Get
				If _CompanyName_W Is Nothing Then
					_CompanyName_W = TearOff.CompanyName
				End If
				Return _CompanyName_W
			End Get
		End Property

		Public ReadOnly Property Phone() As WhereParameter 
			Get
				If _Phone_W Is Nothing Then
					_Phone_W = TearOff.Phone
				End If
				Return _Phone_W
			End Get
		End Property

		Private _ShipperID_W As WhereParameter = Nothing
		Private _CompanyName_W As WhereParameter = Nothing
		Private _Phone_W As WhereParameter = Nothing

		Public Sub WhereClauseReset()

		_ShipperID_W = Nothing
		_CompanyName_W = Nothing
		_Phone_W = Nothing
			Me._entity.Query.FlushWhereParameters()

		End Sub
	
		Private _entity As EasyObject
		Private _tearOff As TearOffWhereParameter
    End Class	

	Public ReadOnly Property Where() As WhereClause
		Get
			If _whereClause Is Nothing Then
				_whereClause = New WhereClause(Me)
			End If
	
			Return _whereClause
		End Get
	End Property
	
	Private _whereClause As WhereClause = Nothing	
#End Region	

#Region " Aggregate Clause "
    Public Class AggregateClause

        Public Sub New(ByVal entity As EasyObject)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffAggregateParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffAggregateParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region " TearOff's "
		Public class TearOffAggregateParameter
		
			Private _clause as AggregateClause
			
			Public Sub New(ByVal clause As AggregateClause)
				Me._clause = clause
			End Sub

			Public ReadOnly Property ShipperID() As AggregateParameter
				Get
					Dim ap As AggregateParameter = New AggregateParameter(ShippersSchema.ShipperID)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddAggregateParameter(ap)
					Return ap
				End Get
			End Property

			Public ReadOnly Property CompanyName() As AggregateParameter
				Get
					Dim ap As AggregateParameter = New AggregateParameter(ShippersSchema.CompanyName)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddAggregateParameter(ap)
					Return ap
				End Get
			End Property

			Public ReadOnly Property Phone() As AggregateParameter
				Get
					Dim ap As AggregateParameter = New AggregateParameter(ShippersSchema.Phone)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddAggregateParameter(ap)
					Return ap
				End Get
			End Property

	End Class
	
	#End Region	

		Public ReadOnly Property ShipperID() As AggregateParameter 
			Get
				If _ShipperID_W Is Nothing Then
					_ShipperID_W = TearOff.ShipperID
				End If
				Return _ShipperID_W
			End Get
		End Property

		Public ReadOnly Property CompanyName() As AggregateParameter 
			Get
				If _CompanyName_W Is Nothing Then
					_CompanyName_W = TearOff.CompanyName
				End If
				Return _CompanyName_W
			End Get
		End Property

		Public ReadOnly Property Phone() As AggregateParameter 
			Get
				If _Phone_W Is Nothing Then
					_Phone_W = TearOff.Phone
				End If
				Return _Phone_W
			End Get
		End Property

		Private _ShipperID_W As AggregateParameter = Nothing
		Private _CompanyName_W As AggregateParameter = Nothing
		Private _Phone_W As AggregateParameter = Nothing

		Public Sub AggregateClauseReset()

		_ShipperID_W = Nothing
		_CompanyName_W = Nothing
		_Phone_W = Nothing
			Me._entity.Query.FlushAggregateParameters()

		End Sub
	
		Private _entity As EasyObject
		Private _tearOff As TearOffAggregateParameter
    End Class	

	Public ReadOnly Property Aggregate() As AggregateClause
		Get
			If _aggregateClause Is Nothing Then
				_aggregateClause = New AggregateClause(Me)
			End If
	
			Return _aggregateClause
		End Get
	End Property
	
	Private _aggregateClause As AggregateClause = Nothing	
#End Region	

End Class


