'===============================================================================
'  Generated From - VbNet_EasyObject_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  
'  This object is 'MustInherit' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  Public Class YourObject 
'      Inherits _YourObject
'
'  End Class
'
'===============================================================================

' Generated by MyGeneration Version # (1.1.4.0)

Imports System
Imports System.Data
Imports System.Configuration
Imports System.Collections
Imports System.Collections.Specialized
Imports System.Xml
Imports System.IO

Imports Microsoft.Practices.EnterpriseLibrary.Data
Imports NCI.EasyObjects


#Region " Schema "

Public Class TerritoriesSchema
	Inherits NCI.EasyObjects.Schema

    Private Shared _entries As ArrayList
	Public Shared TerritoryID As New SchemaItem("TerritoryID", DbType.String, SchemaItemJustify.None, 20, False, True, True, False)
	Public Shared TerritoryDescription As New SchemaItem("TerritoryDescription", DbType.StringFixedLength, SchemaItemJustify.None, 50, False, False, False, False)
	Public Shared RegionID As New SchemaItem("RegionID", DbType.Int32, False, False, False, False, True, False)

    Public Overrides ReadOnly Property SchemaEntries() As ArrayList
        Get
            If _entries Is Nothing Then
                _entries = New ArrayList()
				_entries.Add(TerritoriesSchema.TerritoryID)
				_entries.Add(TerritoriesSchema.TerritoryDescription)
				_entries.Add(TerritoriesSchema.RegionID)

            End If
            Return _entries
        End Get
    End Property

End Class

#End Region

Public MustInherit Class _Territories
    Inherits EasyObject

    Sub New()
        Dim _schema As New TerritoriesSchema()
        Me.SchemaEntries = _schema.SchemaEntries
		Me.SchemaGlobal = "dbo"
    End Sub

	Public Overrides Sub FlushData()
		Me._whereClause = Nothing
		Me._aggregateClause = Nothing
		MyBase.FlushData()
	End Sub
		
	''' <summary>
	''' Loads the business object with info from the database, based on the requested primary key.
	''' </summary>
	''' <param name="TerritoryID"></param>
	''' <returns>A Boolean indicating success or failure of the query</returns>
	Public Function LoadByPrimaryKey(ByVal TerritoryID As String) As Boolean
		
		Select Case Me.DefaultCommandType
			Case CommandType.StoredProcedure
				Dim parameters As ListDictionary = New ListDictionary

				' Add in parameters
				parameters.Add(TerritoriesSchema.TerritoryID.FieldName, TerritoryID)

				Return MyBase.LoadFromSql(Me.SchemaStoredProcedureWithSeparator & "daab_GetTerritories", parameters, CommandType.StoredProcedure)
				
			Case CommandType.Text
				Me.Where.TerritoryID.Value = TerritoryID
				Return Me.Query.Load()

			Case Else
				Throw New ArgumentException("Invalid CommandType", "commandType")
				
		End Select
		
	End Function

    ''' <summary>
    ''' Loads all records from the table.
    ''' </summary>
    ''' <returns>A Boolean indicating success or failure of the query</returns>
    Public Function LoadAll() As Boolean
	
		Select Case Me.DefaultCommandType
		
			Case CommandType.StoredProcedure
				Dim parameters As ListDictionary = Nothing
				Return MyBase.LoadFromSql(Me.SchemaStoredProcedureWithSeparator & "daab_GetAllTerritories", parameters, CommandType.StoredProcedure)
				
			Case CommandType.Text
				Return Me.Query.Load()
			
			Case Else
				Throw New ArgumentException("Invalid CommandType", "commandType")
				
		End Select

    End Function

    ''' <summary>
    ''' Adds a new record to the internal table.
    ''' </summary>
	Public Overrides Sub AddNew()
		MyBase.AddNew()

	End Sub

    Protected Shadows Function GetInsertCommand(commandType As CommandType) As DBCommandWrapper
	
		Dim dbCommandWrapper As DBCommandWrapper
		
        ' Create the Database object, using the default database service. The
        ' default database service is determined through configuration.
        Dim db As Database = GetDatabase()
	
		Select Case commandType
		
			Case CommandType.StoredProcedure
				Dim sqlCommand As String = Me.SchemaStoredProcedureWithSeparator & "daab_AddTerritories"
				dbCommandWrapper = db.GetStoredProcCommandWrapper(sqlCommand)
		
				CreateParameters(dbCommandWrapper)
				
				' Add autokey parameters
				
			Case CommandType.Text
				Me.Where.WhereClauseReset()
				For Each item As SchemaItem In Me.SchemaEntries
					If Not (item.IsAutoKey OrElse item.IsComputed)
						Me.Query.AddInsertColumn(item)
					End If
				Next
				dbCommandWrapper = Me.Query.GetInsertCommandWrapper()

				dbCommandWrapper.Command.Parameters.Clear()
				CreateParameters(dbCommandWrapper)

			Case Else
				Throw New ArgumentException("Invalid CommandType", "commandType")
				
		End Select

        Return dbCommandWrapper

    End Function

    Protected Shadows Function GetUpdateCommand(commandType As CommandType) As DBCommandWrapper
	
		Dim dbCommandWrapper As DBCommandWrapper

        ' Create the Database object, using the default database service. The
        ' default database service is determined through configuration.
        Dim db As Database = GetDatabase()
	
		Select Case commandType
		
			Case CommandType.StoredProcedure
				Dim sqlCommand As String = Me.SchemaStoredProcedureWithSeparator & "daab_UpdateTerritories"
				dbCommandWrapper = db.GetStoredProcCommandWrapper(sqlCommand)
		
				CreateParameters(dbCommandWrapper)
		
				' Add autokey parameters

			Case CommandType.Text
				Me.Where.WhereClauseReset()
				For Each item As SchemaItem In Me.SchemaEntries
					If Not (item.IsAutoKey OrElse item.IsComputed)
						Me.Query.AddInsertColumn(item)
					End If
				Next

				Me.Where.WhereClauseReset()
				dbCommandWrapper = Me.Query.GetUpdateCommandWrapper()

				dbCommandWrapper.Command.Parameters.Clear()
				CreateParameters(dbCommandWrapper)

			Case Else
				Throw New ArgumentException("Invalid CommandType", "commandType")
				
		End Select

        Return dbCommandWrapper

    End Function

    Protected Shadows Function GetDeleteCommand(commandType As CommandType) As DBCommandWrapper
	
		Dim dbCommandWrapper As DBCommandWrapper

        ' Create the Database object, using the default database service. The
        ' default database service is determined through configuration.
        Dim db As Database = GetDatabase()
	
		Select Case commandType
		
			Case CommandType.StoredProcedure
				Dim sqlCommand As String = Me.SchemaStoredProcedureWithSeparator & "daab_DeleteTerritories"
				dbCommandWrapper = db.GetStoredProcCommandWrapper(sqlCommand)
		
				' Add primary key parameters
				dbCommandWrapper.AddInParameter("TerritoryID", DbType.String, "TerritoryID", DataRowVersion.Current)

			Case CommandType.Text
				Me.Where.WhereClauseReset()
			dbCommandWrapper = Me.Query.GetDeleteCommandWrapper()

			dbCommandWrapper.Command.Parameters.Clear()
				dbCommandWrapper.AddInParameter("TerritoryID", DbType.String, "TerritoryID", DataRowVersion.Current)

			Case Else
				Throw New ArgumentException("Invalid CommandType", "commandType")
				
		End Select

        Return dbCommandWrapper

    End Function

    Private Sub CreateParameters(ByVal dbCommandWrapper As DBCommandWrapper)
		
		dbCommandWrapper.AddInParameter("TerritoryID", DbType.String, "TerritoryID", DataRowVersion.Current)
		dbCommandWrapper.AddInParameter("TerritoryDescription", DbType.StringFixedLength, "TerritoryDescription", DataRowVersion.Current)
		dbCommandWrapper.AddInParameter("RegionID", DbType.Int32, "RegionID", DataRowVersion.Current)

    End Sub

#Region " Properties "

	Public Overridable Property TerritoryID() As String
        Get
			Return Me.GetString(TerritoriesSchema.TerritoryID.FieldName)
      End Get
        Set(ByVal Value As String)
			Me.SetString(TerritoriesSchema.TerritoryID.FieldName, Value)
      End Set
    End Property

	Public Overridable Property TerritoryDescription() As String
        Get
			Return Me.GetString(TerritoriesSchema.TerritoryDescription.FieldName)
      End Get
        Set(ByVal Value As String)
			Me.SetString(TerritoriesSchema.TerritoryDescription.FieldName, Value)
      End Set
    End Property

	Public Overridable Property RegionID() As Integer
        Get
			Return Me.GetInteger(TerritoriesSchema.RegionID.FieldName)
      End Get
        Set(ByVal Value As Integer)
			Me.SetInteger(TerritoriesSchema.RegionID.FieldName, Value)
      End Set
    End Property

    Public Overrides ReadOnly Property TableName() As String
        Get
            Return "Territories"
        End Get
    End Property

#End Region

#Region " String Properties "
		Public Overridable Property s_TerritoryID As String
			Get
				If Me.IsColumnNull(TerritoriesSchema.TerritoryID.FieldName) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(TerritoriesSchema.TerritoryID.FieldName)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(TerritoriesSchema.TerritoryID.FieldName)
				Else
					Me.TerritoryID = MyBase.SetStringAsString(TerritoriesSchema.TerritoryID.FieldName, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_TerritoryDescription As String
			Get
				If Me.IsColumnNull(TerritoriesSchema.TerritoryDescription.FieldName) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(TerritoriesSchema.TerritoryDescription.FieldName)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(TerritoriesSchema.TerritoryDescription.FieldName)
				Else
					Me.TerritoryDescription = MyBase.SetStringAsString(TerritoriesSchema.TerritoryDescription.FieldName, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_RegionID As String
			Get
				If Me.IsColumnNull(TerritoriesSchema.RegionID.FieldName) Then
					Return String.Empty
				Else
					Return MyBase.GetIntegerAsString(TerritoriesSchema.RegionID.FieldName)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(TerritoriesSchema.RegionID.FieldName)
				Else
					Me.RegionID = MyBase.SetIntegerAsString(TerritoriesSchema.RegionID.FieldName, Value)
				End If
			End Set
		End Property


#End Region

#Region " Where Clause "
    Public Class WhereClause

        Public Sub New(ByVal entity As EasyObject)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffWhereParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffWhereParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region " TearOff's "
		Public class TearOffWhereParameter
		
			Private _clause as WhereClause
			
			Public Sub New(ByVal clause As WhereClause)
				Me._clause = clause
			End Sub

			Public ReadOnly Property TerritoryID() As WhereParameter
				Get
					Dim wp As WhereParameter = New WhereParameter(TerritoriesSchema.TerritoryID)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddWhereParameter(wp)
					Return wp
				End Get
			End Property

			Public ReadOnly Property TerritoryDescription() As WhereParameter
				Get
					Dim wp As WhereParameter = New WhereParameter(TerritoriesSchema.TerritoryDescription)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddWhereParameter(wp)
					Return wp
				End Get
			End Property

			Public ReadOnly Property RegionID() As WhereParameter
				Get
					Dim wp As WhereParameter = New WhereParameter(TerritoriesSchema.RegionID)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddWhereParameter(wp)
					Return wp
				End Get
			End Property

	End Class
	
	#End Region	

		Public ReadOnly Property TerritoryID() As WhereParameter 
			Get
				If _TerritoryID_W Is Nothing Then
					_TerritoryID_W = TearOff.TerritoryID
				End If
				Return _TerritoryID_W
			End Get
		End Property

		Public ReadOnly Property TerritoryDescription() As WhereParameter 
			Get
				If _TerritoryDescription_W Is Nothing Then
					_TerritoryDescription_W = TearOff.TerritoryDescription
				End If
				Return _TerritoryDescription_W
			End Get
		End Property

		Public ReadOnly Property RegionID() As WhereParameter 
			Get
				If _RegionID_W Is Nothing Then
					_RegionID_W = TearOff.RegionID
				End If
				Return _RegionID_W
			End Get
		End Property

		Private _TerritoryID_W As WhereParameter = Nothing
		Private _TerritoryDescription_W As WhereParameter = Nothing
		Private _RegionID_W As WhereParameter = Nothing

		Public Sub WhereClauseReset()

		_TerritoryID_W = Nothing
		_TerritoryDescription_W = Nothing
		_RegionID_W = Nothing
			Me._entity.Query.FlushWhereParameters()

		End Sub
	
		Private _entity As EasyObject
		Private _tearOff As TearOffWhereParameter
    End Class	

	Public ReadOnly Property Where() As WhereClause
		Get
			If _whereClause Is Nothing Then
				_whereClause = New WhereClause(Me)
			End If
	
			Return _whereClause
		End Get
	End Property
	
	Private _whereClause As WhereClause = Nothing	
#End Region	

#Region " Aggregate Clause "
    Public Class AggregateClause

        Public Sub New(ByVal entity As EasyObject)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffAggregateParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffAggregateParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region " TearOff's "
		Public class TearOffAggregateParameter
		
			Private _clause as AggregateClause
			
			Public Sub New(ByVal clause As AggregateClause)
				Me._clause = clause
			End Sub

			Public ReadOnly Property TerritoryID() As AggregateParameter
				Get
					Dim ap As AggregateParameter = New AggregateParameter(TerritoriesSchema.TerritoryID)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddAggregateParameter(ap)
					Return ap
				End Get
			End Property

			Public ReadOnly Property TerritoryDescription() As AggregateParameter
				Get
					Dim ap As AggregateParameter = New AggregateParameter(TerritoriesSchema.TerritoryDescription)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddAggregateParameter(ap)
					Return ap
				End Get
			End Property

			Public ReadOnly Property RegionID() As AggregateParameter
				Get
					Dim ap As AggregateParameter = New AggregateParameter(TerritoriesSchema.RegionID)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddAggregateParameter(ap)
					Return ap
				End Get
			End Property

	End Class
	
	#End Region	

		Public ReadOnly Property TerritoryID() As AggregateParameter 
			Get
				If _TerritoryID_W Is Nothing Then
					_TerritoryID_W = TearOff.TerritoryID
				End If
				Return _TerritoryID_W
			End Get
		End Property

		Public ReadOnly Property TerritoryDescription() As AggregateParameter 
			Get
				If _TerritoryDescription_W Is Nothing Then
					_TerritoryDescription_W = TearOff.TerritoryDescription
				End If
				Return _TerritoryDescription_W
			End Get
		End Property

		Public ReadOnly Property RegionID() As AggregateParameter 
			Get
				If _RegionID_W Is Nothing Then
					_RegionID_W = TearOff.RegionID
				End If
				Return _RegionID_W
			End Get
		End Property

		Private _TerritoryID_W As AggregateParameter = Nothing
		Private _TerritoryDescription_W As AggregateParameter = Nothing
		Private _RegionID_W As AggregateParameter = Nothing

		Public Sub AggregateClauseReset()

		_TerritoryID_W = Nothing
		_TerritoryDescription_W = Nothing
		_RegionID_W = Nothing
			Me._entity.Query.FlushAggregateParameters()

		End Sub
	
		Private _entity As EasyObject
		Private _tearOff As TearOffAggregateParameter
    End Class	

	Public ReadOnly Property Aggregate() As AggregateClause
		Get
			If _aggregateClause Is Nothing Then
				_aggregateClause = New AggregateClause(Me)
			End If
	
			Return _aggregateClause
		End Get
	End Property
	
	Private _aggregateClause As AggregateClause = Nothing	
#End Region	

End Class


